### ISSUE TITLE
InfluxBolt unable to parse time in UTC

### ISSUE THREAD

**Issue by prashantsachan-unbxd** [unbxd/ala#45]
2017-06-07 14:38:38.303 c.u.m.a.b.InfluxBolt [ERROR] java.text.ParseException: Unparseable date: "2017-06-07T14:38:37.625-06-07T14:38:37.625427252Z"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at com.unbxd.monitoring.alaStorm.bolt.InfluxBolt.toLong(InfluxBolt.java:87)
	at com.unbxd.monitoring.alaStorm.bolt.InfluxBolt.execute(InfluxBolt.java:65)
	at org.apache.storm.daemon.executor$fn__8058$tuple_action_fn__8060.invoke(executor.clj:731)
	at org.apache.storm.daemon.executor$mk_task_receiver$fn__7979.invoke(executor.clj:464)
	at org.apache.storm.disruptor$clojure_handler$reify__7492.onEvent(disruptor.clj:40)
	at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:451)
	at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:430)
	at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:73)
	at org.apache.storm.daemon.executor$fn__8058$fn__8071$fn__8124.invoke(executor.clj:850)
	at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:484)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)

2017-06-07 14:39:40.317 o.a.s.k.ZkCoordinator [INFO] Task [1/1] Finished refreshing
2017-06-07 14:39:41.286 STDIO [INFO] received : {"service":{"id":"solr-4-164","host":"http://54.210.4.164","port":8086,"class":["solr"],"metadata":null},"timestamp":"2017-06-07T14:39:40.625628348Z","metricName":"HTTPstatus200","value":1}
2017-06-07 14:39:41.286 STDIO [ERROR] java.text.ParseException: Unparseable date: "2017-06-07T14:39:40.625-06-07T14:39:40.625628348Z"
2017-06-07 14:39:41.286 STDIO [ERROR] at java.text.DateFormat.parse(DateFormat.java:366)

**Comment by prashantsachan-unbxd** [comment]
this is happening because we are using UTC timezone in production, hence the timezone info is omitted from the timestamp. parsing it with dateformat `"yyyy-MM-dd'T'HH:mm:ss.SSSXXX"` causes this problem
